---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-fstorages
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-fstorages 
subsets:
  - addresses:
      - ip: 167.172.100.36 
    ports:
      - port: 1
