apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodejs-pv
  annotations:
    pv.beta.kubernetes.io/gid: "0" 
spec:
  capacity:
    storage: 15Gi
  accessModes: 
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-fstorages
    path: pv01
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
